const design = {
    add:{
        navbar:()=>{
            createNavbar();
        },
    },
}

let navbar_status;
let added_inner;
function createNavbar() {
    added_inner = document.querySelector("#added").innerHTML;
    document.querySelector("#added").innerHTML = "<nav id=\"autogeneratednavbar\" class=\"auto - navbar -default \"><ul><li><a>HOME PAGE</a></li><li><a>MAIN PAGE</a></li></ul ></nav >" + added_inner;
    navbar_status = "created";
}